# Generated by Django 4.2.9 on 2024-01-18 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("telephone", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="LigneVente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantite_stock", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_vente", models.DateField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stockage.client",
                    ),
                ),
                (
                    "produits",
                    models.ManyToManyField(
                        through="stockage.LigneVente", to="stockage.produit"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lignevente",
            name="produit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stockage.produit"
            ),
        ),
        migrations.AddField(
            model_name="lignevente",
            name="vente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="stockage.vente"
            ),
        ),
        migrations.CreateModel(
            name="Achat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                ("date_achat", models.DateField(auto_now_add=True)),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stockage.fournisseur",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stockage.produit",
                    ),
                ),
            ],
        ),
    ]
